### PR TITLE
Fix interrupt issue

### PR DESCRIPTION
**Pull request by qhuyduong**
Interrupt mode is now working

### CODE REVIEW

**Comment by ExtremeXT** [comment]
@qhuyduong Does this work, or is it a WIP? Can you provide any compiled builds for testing purposes?

**Comment by qhuyduong** [comment]
@ExtremeXT yes it's working for me. You can try this. Place it inside VoodooI2C.kext/Contents/PlugIns
[VoodooGPIO.zip](https://github.com/NootInc/VoodooGPIO/files/11857842/VoodooGPIO.zip)

**Comment by ExtremeXT** [comment]
> @ExtremeXT yes it's working for me. You can try this. Place it inside VoodooI2C.kext/Contents/PlugIns
> [VoodooGPIO.zip](https://github.com/NootInc/VoodooGPIO/files/11857842/VoodooGPIO.zip)
> 

Works well for now, thanks!

**Comment by ChefKissInc** [comment]
Do you have an explanation for why this works? I just now tried changing the order and calling the ire enable function first and it did not work

**Pull request closed without merging**
